Add basePath documentation
flightcontrolhq/website pull request #81
Opened 2023-02-07 10:20 UTC by crondinini

## Description

Write up for the new supported field `basePath` that will allow people to specify in which folder the `nixpacks` build command should run. Mainly added for better supporting monorepos.

2023-02-07 10:43 UTC, flybayer requested changes

2023-02-07 10:43 UTC, flybayer commented on motif-docs/pages/guides/config/monorepos.mdx
> +                                     Left for illustration purpose
```suggestion
          "installCommand": "cd .. && npm ci"
          "basePath": "packages/api", 
```

2023-02-07 10:43 UTC, flybayer commented on motif-docs/pages/guides/config/monorepos.mdx
> +If for some reason `nixpacks` cannot identify the `[install|build|start]Command`, you'll then need to manually add it.
it won't, so they almost certainly need to add this

2023-02-07 10:43 UTC, flybayer commented on motif-docs/pages/guides/config/monorepos.mdx
>  }
Instead of using `NIXPACKS_CONFIG_FILE`, they should define `basePath` to the service, and then add `nixpacks.toml` in that basePath location.

2023-02-08 05:05 UTC, flybayer commented on motif-docs/pages/guides/config/monorepos.mdx
> +If you don't use any sort of monorepo tooling at the root of your repo, then you should indicate a `basePath` alongside the `[install|build|start]` commands, like illustrated in the contrived config
```suggestion
Most users should define a `basePath` alongside the `[install|build|start]` commands, as illustrated below.
```

2023-02-08 05:31 UTC, crondinini commented on motif-docs/pages/guides/config/monorepos.mdx
> +If you don't use any sort of monorepo tooling at the root of your repo, then you should indicate a `basePath` alongside the `[install|build|start]` commands, like illustrated in the contrived config
Fixes as we discussed

2023-02-08 09:24 UTC, flybayer approved these changes

2023-02-08 09:34 UTC, merged